### ISSUE TITLE
BackstopJS Report doesn't fire up after more than 999 tests

### ISSUE THREAD

**Issue by stephenbe** [garris/BackstopJS#329] opened 2016-10-27 18:43 UTC
Hey @garris,

At 1000 tests and more, the BackstopJS Report doesn't work anymore. I tested it locally at 999 it works and at 1000 it fails.

I don't have any errors. 

This what I get in the CMD : 

```
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?backstop=tru
e#graphiques
CasperJS:  Capturing screenshots for desktop (1280x1014)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?backstop=tru
e&touch=true#graphiques
CasperJS:  Capturing screenshots for phone (320x480)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?backstop=tru
e&touch=true#graphiques
CasperJS:  Capturing screenshots for tablet_v (768x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?backstop=tru
e&touch=true#graphiques
CasperJS:  Capturing screenshots for tablet_h (1024x768)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?backstop=tru
e&touch=true#graphiques
CasperJS:  Capturing screenshots for desktop (1280x1014)
CasperJS:  Comparison config file updated.

Bitmap file generation completed.
COMMAND | Executing core for `report`

C:\Projets\N3\fwd-webapp-overlay-skin>

```

Thanks!

**Comment by garris** [comment] 2016-10-27 18:54
oof.  hmm.  😕

There is no business logic (that I know of) which would cause that.

There are other reports of issues with a lot of tests running in general however.   e.g. #281 

Do you have a publicly available version of your app that I could run your tests against?   I would like to take a look at it.

A work around would probably be to break up your tests into multiple configs and batch them on the command line...

```
$ backstop test --path=./myAdminFeatures && backstop test --path=./mySearchFeatures && backstop test --path=./myFeedFeatures
```

**Comment by stephenbe** [comment] 2016-10-27 19:26
@garris hmm interestingly, my colleague doesn't have the problem. I will report back with more insight, it might be my computer.

Thanks for the quick reply

**Comment by garris** [comment] 2016-10-27 20:32
It could be a memory problem -- your colleague might have more of it.   It would be interesting to see if any of the suggestions in #281 fix the issue.

**Comment by stephenbe** [comment] 2016-10-28 14:33
Hey Garris,

I sent you an email with the app. My colleague has the same problem, but it takes a bit more than a 1000...I think you might be right about memory...For now we will separate the tasks. 

Thank you for your help! Once 281 is fixed, I will be able to give it a shot once more.

**Comment by stephenbe** [comment] 2016-10-28 14:43
by the way, I still think this is hands down the best regression tester on the market by far! Thank you for giving us this awesome tool.

**Comment by stephenbe** [comment] 2016-10-28 15:29
@garris another idea is instead of chaining commands in the CMD, make it that backstop can  run multiple tasks with one command like gulp.

What do you think?

**Comment by PhilippeVay** [comment] 2016-11-02 09:14
You can have different JSON files https://github.com/garris/BackstopJS#setting-the-config-file-path (and reference+test directories). 1 per viewport maybe? That'd allow you to launch multiple commands like `b1 & b2 & b3 &` in Bash or `start cmd /k call yourcommand` in Windows cmd.exe. Problem is you'll run out of memory even faster so some of your commands should be faster to run than others :)
Not sure if [Filip Bartoš use of gulp-chug](http://blog.bartos.me/css-regression-testing/) is still relevant?

**Comment by garris** [comment] 2016-11-02 19:24
@PhilippeVay whoops!  you are right!   What I meant was sperating commands by semicolon (not ampersands)

```
$ backstop test --path=./myAdminFeatures ; backstop test --path=./mySearchFeatures ; backstop test --path=./myFeedFeatures
```

**Comment by garris** [comment] 2016-11-02 19:26
@stephenbe sorry for the delay with your response.   I have some time booked on he 4th specifically to work on this one.  Thanks for your patience!

**Comment by stephenbe** [comment] 2016-11-02 19:31
@garris Thanks garris, I never take your help for granted, take all the time you need, but I appreciate that you booked some time just for this one.

Can you check your mail and download my app, the wetransfer link will expire in 24 hours haha.

**Comment by garris** [comment] 2016-11-02 21:40
@stephenbe got it ✅

**Comment by garris** [comment] 2016-11-04 21:44
Ok.  I was able to run the app.  After bitmaps were generated the comparison process ran and grew steadily to 5+Gig.  Still investigating.

**Comment by stephenbe** [comment] 2016-11-04 21:54
Thanks @garris ! If you need anything, let me know!!

**Comment by garris** [comment] 2016-11-09 18:19
@stephenbe I just wanted to follow up.   I attempted to throttle concurrent comparisons but the memory leak persisted.  I committed this code here https://github.com/garris/BackstopJS/commit/adc2ae2373bdeb99fea6bb0f678da8c044127330 even though this approach did not immediately solve the issue.  What I believe is that each `resemble` object is generating _and caching_ a comparison image -- holding that in RAM while all comparisons are running.   I think the next thing to try is to refactor this flow such that references to each `resemble` object are completely cleaned up once a write to `fs` is complete.   I am hoping that would make backstop MUCH more RAM efficient.  The good news is that once map is complete all instances are cleaned up and memory is completely returned.   So I am confident that this issue is addressable.  Will just take a little effort to get the sequencing right.

Would appreciate any help here from anyone who is interested.   Otherwise I will try to get to this in January.

**Comment by garris** [comment] 2016-11-22 19:04
@stephenbe looks like @paradizex posted a fix!   

I am about to travel for a week and won't have time to review -- would help if you have some time to apply the patch and test.   If not -- I will review when I get back.

Cheers!

**Closed** 2016-11-28 21:35 UTC
Labels: bug, help wanted

**Comment by garris** [comment] 2016-11-29 06:46
@stephenbe Thanks for your patience -- this is fixed!

Thank you very much for sharing your massive test project -- It was very helpful in ensuring that this issue is in-fact settled.

It's currently in beta -- please give this a try and let me know if this fixes your memory issue.
```
npm install -g backstopjs@beta
```

More info... https://github.com/garris/BackstopJS/releases/tag/v2.3.4

**Comment by stephenbe** [comment] 2016-11-29 14:46
Hey @garris !

I am so sorry, I did not see your comment above posted 7 days ago. I will test this today and let you know!

Thank you so much!!! BackstopJS is getting better and better, it's exciting! :+1:

**Comment by stephenbe** [comment] 2016-11-30 16:21
@garris I just tested it and it works now!

Thank you so much from the bottom of my heart for this amazing tool and support! I really appreciate and I think I can speak for this community that we all appreciate your hard work. 

Thank you! :)

**Comment by garris** [comment] 2016-11-30 17:26
Cheers! 😀
