### ISSUE TITLE
bitmap_reference folder not being created and erroring out while running reference.

### ISSUE THREAD

**Issue by marlin307** [garris/BackstopJS#277] opened 2016-08-30 20:43 UTC
C:\vrb\node_modules\backstopjs>npm run genConfig

> backstopjs@1.3.5 genConfig C:\vrb\node_modules\backstopjs
> gulp genConfig

BackstopJS Config loaded at location C:\vrb\backstop.json
[16:35:20] Using gulpfile C:\vrb\node_modules\backstopjs\gulpfile.js
[16:35:20] Starting 'genScripts'...
[16:35:20] Finished 'genScripts' after 30 ms
[16:35:20] Starting 'genConfig'...
[16:35:20] Finished 'genConfig' after 8.03 ms

C:\vrb\node_modules\backstopjs>npm run reference

> backstopjs@1.3.5 reference C:\vrb\node_modules\backstopjs
> gulp reference

BackstopJS Config loaded at location C:\vrb\backstop.json
[16:35:27] Using gulpfile C:\vrb\node_modules\backstopjs\gulpfile.js
[16:35:27] Starting 'clean'...
bitmaps_reference was cleaned.
[16:35:27] Starting 'bless'...
[16:35:27] Finished 'bless' after 4.29 ms
[16:35:27] Finished 'clean' after 16 ms
[16:35:27] Starting 'reference'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task trigger
ing instead.
[16:35:27] Starting 'init'...
[16:35:27] Finished 'init' after 5.31 µs
[16:35:27] Starting 'test'...

Generating reference files.

Running CasperJS with:  [ 'capture/genBitmaps.js' ]
[16:35:27] Finished 'test' after 9.82 ms
reference has run.
[16:35:27] Finished 'reference' after 13 ms

Testing script failed with code: 1

Looks like an error occured. You may want to try running `$ npm run echo`. This
will echo the requested test URL output to the console. You can check this outpu
t to verify that the file requested is indeed being received in the expected for
mat.

C:\vrb\node_modules\backstopjs>

**Comment by danemacaulay** [comment] 2016-09-01 15:34
try setting `debug` to true
https://github.com/garris/BackstopJS#debugging

**Comment by firmlybelieve** [comment] 2016-09-06 01:40
I have the same problem.when i install python, it's all right.

**Comment by robertmazzo** [comment] 2016-09-07 13:12
I have the same problem, with the same exact output as the OP. I will install python as per @firmlybelieve .

**Comment by danemacaulay** [comment] 2016-09-07 16:26
You can also check that phantomjs runs as expected apart from backdrop, you may get more useful error messages

**Comment by robertmazzo** [comment] 2016-09-07 16:32
@danemacaulay - How would I check phantonjs independently ?
And BTW, when I run a `npm ls` to check my installed packages, I get lots of errors. Perhaps I need to run a `npm install` to pull in these packages ? I thought they would have been resolved by the backdropjs install.

backstopjs@1.3.5 C:\Bob\dev\pluralsight\backstopjs-test\myCoolProject\node_modul
es\backstopjs
+-- UNMET DEPENDENCY casperjs@^1.1.0-beta5
+-- UNMET DEPENDENCY checksum@^0.1.1
+-- UNMET DEPENDENCY del@^0.1.3
+-- UNMET DEPENDENCY express@^3.8.1
+-- UNMET DEPENDENCY fs-extra@^0.12.0
+-- UNMET DEPENDENCY gulp@^3.8.8
+-- UNMET DEPENDENCY gulp-jscs@^1.6.x
+-- UNMET DEPENDENCY gulp-jscs-stylish@^1.1.x
+-- UNMET DEPENDENCY gulp-jshint@^1.11.x
+-- UNMET DEPENDENCY gulp-json-editor@^2.2.1
+-- UNMET DEPENDENCY gulp-open@^0.3.0
+-- UNMET DEPENDENCY gulp-rename@^1.2.0
+-- UNMET DEPENDENCY http-proxy@~1.1.4
+-- UNMET DEPENDENCY is-running@~1.0.5
+-- UNMET DEPENDENCY junitwriter@~0.3.1
+-- UNMET DEPENDENCY node-resemble-js@0.0.4
+-- UNMET DEPENDENCY phantomjs-prebuilt@^2.1.7
+-- UNMET DEPENDENCY require-dir@^0.1.0
+-- UNMET DEPENDENCY underscore@~1.6.0
`-- UNMET DEPENDENCY yargs@~3.9.0

npm ERR! missing: casperjs@^1.1.0-beta5, required by backstopjs@1.3.5
npm ERR! missing: checksum@^0.1.1, required by backstopjs@1.3.5
npm ERR! missing: del@^0.1.3, required by backstopjs@1.3.5
npm ERR! missing: express@^3.8.1, required by backstopjs@1.3.5
npm ERR! missing: fs-extra@^0.12.0, required by backstopjs@1.3.5
npm ERR! missing: gulp@^3.8.8, required by backstopjs@1.3.5
npm ERR! missing: gulp-jscs@^1.6.x, required by backstopjs@1.3.5
npm ERR! missing: gulp-jscs-stylish@^1.1.x, required by backstopjs@1.3.5
npm ERR! missing: gulp-jshint@^1.11.x, required by backstopjs@1.3.5
npm ERR! missing: gulp-json-editor@^2.2.1, required by backstopjs@1.3.5
npm ERR! missing: gulp-open@^0.3.0, required by backstopjs@1.3.5
npm ERR! missing: gulp-rename@^1.2.0, required by backstopjs@1.3.5
npm ERR! missing: http-proxy@~1.1.4, required by backstopjs@1.3.5
npm ERR! missing: is-running@~1.0.5, required by backstopjs@1.3.5
npm ERR! missing: junitwriter@~0.3.1, required by backstopjs@1.3.5
npm ERR! missing: node-resemble-js@0.0.4, required by backstopjs@1.3.5
npm ERR! missing: phantomjs-prebuilt@^2.1.7, required by backstopjs@1.3.5
npm ERR! missing: require-dir@^0.1.0, required by backstopjs@1.3.5
npm ERR! missing: underscore@~1.6.0, required by backstopjs@1.3.5
npm ERR! missing: yargs@~3.9.0, required by backstopjs@1.3.5

C:\Bob\dev\pluralsight\backstopjs-test\myCoolProject\node_modules\backstopjs>

**Comment by danemacaulay** [comment] 2016-09-07 18:06
The getting started page can get you there:
http://phantomjs.org/quick-start.html

Bear in mind that backstop installs the phantomjs binary as a node module and it can be run from there after an `npm install` with `./node_modules/.bin/phantomjs`

In Windows I guess the `/`s are `\`

**Comment by robertmazzo** [comment] 2016-09-07 18:24
@danemacaulay I've already tested phantom as I briefly stated above. At this point I'm stuck with the same error after running `npm run reference` . I'm not sure where to go at this point. Thank you.

**Comment by danemacaulay** [comment] 2016-09-07 18:29
oh sry misread that, ive experienced this generic message before `Testing script failed with code: 1` but was able to get more info with the `debug` property set to true

feel like error handling could be improved to give more specific failure messages

**Comment by robertmazzo** [comment] 2016-09-07 18:35
Even with debug: true in backstop.json, I'm getting the same output.
The closest I can get to an exception in the code is this casperChild.on event in `test.js` :

casperChild.on('close', function (code) {
    var success = code === 0; // Will be 1 in the event of failure
    var result = (success)?'Bitmap file generation completed.':'Testing script failed with code: '+code;

    console.log('\n'+result);

    //exit if there was some kind of failure in the casperChild process
    if(code!=0){
      console.log('\nLooks like an error occured. You may want to try running `$ npm run echo`. This will echo the requested test URL output to the console. You can check this output to verify that the file requested is indeed being received in the expected format.');
      return false;
    }

    if(genReferenceMode){
      console.log('\nRun `$ npm run test` to generate diff report.\n')
    }else{
      gulp.run('report');
    }

  });

**Comment by danemacaulay** [comment] 2016-09-07 18:36
that error code number may be useful

**Comment by garris** [comment] 2016-09-08 04:01
@robertmazzo   thanks for being so active about finding a solution.   I don't have easy access to a win box so it's a little hard for me to help.  But my question is this:   Can phantomjs save a screenshot in the directory you are intending to use for reference.   We really should know this first -- from your response above it appears that you are only testing for the existance of phantomjs.   Please just quickly test it phantom can vist Google and take a screenshot.   You can easily find an example online.   Please test that and let me know -- it will lead to an answer.

**Comment by garris** [comment] 2016-09-08 04:03
If the issue is backstop then you might try to install backstop version 2.   It is a global install now with a brand new core -- Gulp has been removed.

**Comment by garris** [comment] 2016-09-08 04:04
But first test phantomjs ;)

**Comment by robertmazzo** [comment] 2016-09-08 14:27
@garris Thanks for following up. I'll try and find time to test the phantomjs screenshot today.

**Comment by garris** [comment] 2016-09-28 19:27
I have just verified that a fresh install of BackstopJS version 2.0 on win10 is working.  Please reopen if you have any other issues.  Cheers.  Garris

**Closed by garris** 2016-09-28 19:27 UTC
