### ISSUE TITLE
Docker arm64 support (Apple Silicon M1)

### ISSUE THREAD

**Issue by felixblaschke** [garris/BackstopJS#1300] opened 2021-04-13 12:43 UTC
The currently available docker images are only available to _amd64_ architecture:
https://hub.docker.com/r/backstopjs/backstopjs/tags?page=1&ordering=last_updated

Soon Apple will change to architecture of all Macbooks to **arm64**. The current Macbook Pro 13 inch is already available with the M1 processor.

Therefore we need backstopjs images that are compatible with **arm64**.

**Comment by garris** [comment] 2021-04-19 16:18
@felixblaschke -- What's your recommendation?   What needs to happen?

**Comment by felixblaschke** [comment] 2021-04-21 07:47
We need to wait for release of https://github.com/puppeteer/puppeteer/pull/7099 because otherwise can't even `npm install` backstop, because of installation failures. (chrome binaries not found).

Then we need to configure the docker image to work with arm64 linux images. The `node` base image already supports that: https://hub.docker.com/_/node?tab=tags&page=1&ordering=last_updated

Next the built backstop docker image needs to be multi-arch build. (https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)

**Comment by torbenberger** [comment] 2021-06-30 13:03
@garris now that step 1 that was described by @felixblaschke seems to be resolved, how can we get m1 support? who can take the next steps?

**Comment by garris** [comment] 2021-06-30 15:26
Thanks @torbenberger, my question is, will the new image be backwards compatible?

If the new assets _will_ be backwards compatible then you would just need to rework the build scripts and create a pull request for me.  

I don't have an M1 device so I'd need you to validate the new builds.

Does that make sense?

**Comment by torbenberger** [comment] 2021-07-15 07:53
@garris what do you mean by backwards compatible? not quite understanding tbh. 

i have an m1 mac so i could validate the new builds :-)

**Comment by garris** [comment] 2021-07-15 14:11
Hi @torbenberger,  sorry,  my question is, will the new image continue to work on non-M1 hardware?

**Comment by torbenberger** [comment] 2021-07-15 14:13
@garris 
i think there is something called "multi arch images" but this produces different images for amd64 and arm64 cpus afaik. so i think we would need to have 2 images to support both architectures. but probably someone with more docker and multiarch knowledge can bring light to the darkness on this topic. i'm not that experience with that

**Comment by garris** [comment] 2021-07-23 15:20
@torbenberger yes,  I am not super knowledgeable about docker or M1 -- I don't want to break existing implementations so I just need someone to explain how this would work.

**Comment by apswak** [comment] 2021-08-24 15:52
Hi Was any progress made on this?

**Comment by garris** [comment] 2021-08-24 22:56
@apswak no progress here.  I am a high-level docker user -- so I would need help to understand the most compatible way I can add support for this. 

(This is a little baffling since I thought docker is supposed to solve the hardware abstraction  problem 🤷‍♂️)

**Comment by cdeutsch** [comment] 2021-11-01 17:41
Shoot. Just ran into this after getting a new laptop (which is going to become more common with the new MacBook Pros out)

@felixblaschke any guidance you can add for updating the Docker image?

**Comment by felixblaschke** [comment] 2021-11-01 17:49
> Shoot. Just ran into this after getting a new laptop (which is going to become more common with the new MacBook Pros out)
> 
> @felixblaschke any guidance you can add for updating the Docker image?

No sorry, I use a secondary intel device or VM to execute tests.

**Comment by cdeutsch** [comment] 2021-11-01 22:10
I was able to get Backstop `v4.3.2` to run on my M1 by adding the following to  my config:

- added `--single-process` to `engineOptions`
- added `--platform linux/amd64` to `dockerCommandTemplate` (OPTIONAL, removes a warning)

Example config: 

```js
{
  dockerCommandTemplate:
    'docker run --rm -it --net="host" --platform linux/amd64 --mount type=bind,source="{cwd}",target=/src backstopjs/backstopjs:{version} {backstopCommand} {args}',
  engine: 'puppeteer',
  engineOptions: {
    args: ['--no-sandbox', '--single-process'],
  }
}
```

I didn't have luck getting `v5.4.4` to work.

**Comment by garris** [comment] 2021-11-02 02:59
@cdeutsch what error did you get with v5.4.4?

**Comment by cdeutsch** [comment] 2021-11-02 20:06
@garris puppeteer isn't starting. Looks like it won't go into Single Threaded mode.

```
COMMAND | Executing core for "test"
createBitmaps | Selected 30 of 30 scenarios.
      COMMAND | Command "test" ended with an error after [1.575s]
      COMMAND | Error: Failed to launch the browser process!
                [1102/200139.436316:ERROR:stack_trace_posix.cc(676)] Failed to parse the contents of /proc/self/maps
                [1102/200139.686485:ERROR:stack_trace_posix.cc(676)] Failed to parse the contents of /proc/self/maps
                [1102/200139.686638:ERROR:stack_trace_posix.cc(676)] Failed to parse the contents of /proc/self/maps
                [1102/200139.711694:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded().
                #0 0x004006aa0f49 base::debug::CollectStackTrace()
                #1 0x004006a0a933 base::debug::StackTrace::StackTrace()
                #2 0x004006a1e500 logging::LogMessage::~LogMessage()
                #3 0x004006a1f04e logging::LogMessage::~LogMessage()
                #4 0x0040065bea27 content::ZygoteMain()
                #5 0x0040065b9ae5 content::RunZygote()
                #6 0x0040065bafcb content::ContentMainRunnerImpl::Run()
                #7 0x0040065b87cb content::RunContentProcess()
                #8 0x0040065b90cd content::ContentMain()
                #9 0x004006618136 headless::(anonymous namespace)::RunContentMain()
                #10 0x004006617e93 headless::RunChildProcessIfNeeded()
                #11 0x004006616af5 headless::HeadlessShellMain()
                #12 0x00400342bae1 ChromeMain
                #13 0x004012b402e1 __libc_start_main
                #14 0x00400342b92a _start

                [1102/200139.711694:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded().
                #0 0x004006aa0f49 base::debug::CollectStackTrace()
                #1 0x004006a0a933 base::debug::StackTrace::StackTrace()
                #2 0x004006a1e500 logging::LogMessage::~LogMessage()
                #3 0x004006a1f04e logging::LogMessage::~LogMessage()
                #4 0x0040065bea27 content::ZygoteMain()
                #5 0x0040065b9ae5 content::RunZygote()
                #6 0x0040065bafcb content::ContentMainRunnerImpl::Run()
                #7 0x0040065b87cb content::RunContentProcess()
                #8 0x0040065b90cd content::ContentMain()
                #9 0x004006618136 headless::(anonymous namespace)::RunContentMain()
                #10 0x004006617e93 headless::RunChildProcessIfNeeded()
                #11 0x004006616af5 headless::HeadlessShellMain()
                #12 0x00400342bae1 ChromeMain
                #13 0x004012b402e1 __libc_start_main
                #14 0x00400342b92a _start

                Received signal 6
                Received signal 6
                #0 0x004006aa0f49 #0 0x004006aa0f49 base::debug::CollectStackTrace()
                #1 0x004006a0a933 base::debug::CollectStackTrace()
                #1 0x004006a0a933 base::debug::StackTrace::StackTrace()
                #2 0x004006aa0a21 base::debug::StackTrace::StackTrace()
                #2 0x004006aa0a21 base::debug::(anonymous namespace)::StackDumpSignalHandler()base::debug::(anonymous namespace)::StackDumpSignalHandler()

                ##33  0x0x00400e3270e000400e3270e0  <unknown><unknown>

                ##44  0x0x004012b52fff004012b52fff  gsignalgsignal

                ##55  0x0x004012b5442a004012b5442a  abort
                #6 0x004006a9fcb5 abort
                #6 0x004006a9fcb5 base::debug::BreakDebugger()
                #7 0x004006a1e927 base::debug::BreakDebugger()
                #7 0x004006a1e927 logging::LogMessage::~LogMessage()logging::LogMessage::~LogMessage()

                ##88  0x0x004006a1f04e004006a1f04e  logging::LogMessage::~LogMessage()logging::LogMessage::~LogMessage()

                ##99  0x0x0040065bea270040065bea27  content::ZygoteMain()content::ZygoteMain()

                ##10 100x 0x0040065b9ae5 0040065b9ae5 content::RunZygote()
                #11 0x0040065bafcb content::RunZygote()
                #11 0x0040065bafcb content::ContentMainRunnerImpl::Run()
                #12content::ContentMainRunnerImpl::Run()
                0x#0040065b87cb12  0x0040065b87cb content::RunContentProcess()
                #13 0x0040065b90cd content::RunContentProcess()
                #13 0x0040065b90cd content::ContentMain()
                #14 0x004006618136 content::ContentMain()
                #14 0x004006618136 headless::(anonymous namespace)::RunContentMain()
                #15 0x004006617e93 headless::(anonymous namespace)::RunContentMain()
                #15 0x004006617e93 headless::RunChildProcessIfNeeded()
                #16 0x004006616af5 headless::RunChildProcessIfNeeded()
                #16 0x004006616af5 headless::HeadlessShellMain()headless::HeadlessShellMain()

                ##1717  0x0x00400342bae100400342bae1  ChromeMainChromeMain

                ##1818  0x0x004012b402e1004012b402e1  __libc_start_main
                #19 0x__libc_start_main00400342b92a
                #19 0x00400342b92a _start
                  r8: 0000000000000000  r9: 000000400deda550 r10: 0000000000000008 r11: 0000165c002d032e
                 r12: 0000165c002e4500 r13: 000000400deda7a0 r14: 0000165c002e4510 r15: aaaaaaaaaaaaaaaa
                  di: 0000000000000002  si: 000000400deda550  bp: 000000400deda790  bx: 0000000000000006
                  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 000000400deda5c8
                  ip: 0000004012b52fff efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
                 trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
                _start
                  r8: [end of stack trace]
                0000000000000000  r9: 000000400deda530 r10: 0000000000000008 r11: 0000156a002d032e
                 r12: 0000156a002e4500 r13: 000000400deda780 r14: 0000156a002e4510 r15: aaaaaaaaaaaaaaaa
                  di: 0000000000000002  si: 000000400deda530  bp: 000000400deda770  bx: 0000000000000006
                  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 000000400deda5a8
                  ip: 0000004012b52fff efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
                 trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
                [end of stack trace]
                qemu: uncaught target signal 6 (Aborted) - core dumped
                qemu: uncaught target signal 6 (Aborted) - core dumped
                Received signal 11 SEGV_MAPERR 2f736a706f7473
                #0 0x004006aa0f49 base::debug::CollectStackTrace()
                #1 0x004006a0a933 base::debug::StackTrace::StackTrace()
                #2 0x004006aa0a21 Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
                base::debug::(anonymous namespace)::StackDumpSignalHandler()
                #3 0x00400e3270e0 <unknown>
                #4 0x004006c18250 event_base_loop
                #5 0x004006ad4e00 base::MessagePumpLibevent::Run()
                #6 0x004006a75475 qemu: uncaught target signal 11 (Segmentation fault) - core dumped


                TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

                    at onClose (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
                    at Interface.<anonymous> (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
                    at Interface.emit (events.js:387:35)
                    at Interface.close (readline.js:451:8)
                    at Socket.onend (readline.js:224:10)
                    at Socket.emit (events.js:387:35)
                    at endReadableNT (internal/streams/readable.js:1317:12)
                    at processTicksAndRejections (internal/process/task_queues.js:82:21)
COMMAND | Executing core for "openReport"
openReport | Attempting to ping
   COMMAND | Command "test" ended with an error after [38.84s]
   COMMAND | Error: docker run --rm -it --net="host" --mount type=bind,source="/Users/me/work/source/frontend-e2e-tests",target=/src backstopjs/backstopjs:5.4.4 test "--moby" "--config=backstop_data/dist/dashConfig" returned 1
                 at ChildProcess.<anonymous> (/Users/me/work/source/frontend-e2e-tests/node_modules/backstopjs/core/util/runDocker.js:68:18)
                 at ChildProcess.emit (node:events:394:28)
                 at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
openReport | Remote not found. Opening backstop_data/html_report/index.html
```

**Comment by garris** [comment] 2021-11-02 21:14
@cdeutsch as a forward fix, maybe a newer version of puppeteer might address this issue?

**Comment by cdeutsch** [comment] 2021-11-03 00:48
I was able to build an M1 compatible Docker image by doing the following:

- Add `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true` to `npm install backstopjs` to prevent it from hitting an issue with no ARM version of chromium existing.
- Add `chromium` to list of apt-get packages

![Screen Shot 2021-11-02 at 6 04 00 PM](https://user-images.githubusercontent.com/404765/139963806-d8ab4f44-b1da-429c-8e3a-89e9cd9389e6.png)

- Update `build-docker` to run `docker buildx build` instead of `docker build`

![image](https://user-images.githubusercontent.com/404765/139964343-8c0652dd-1303-466a-975f-0117cc65595d.png)

- In my project change the puppeteer `executablePath` for chromium to `/usr/bin/chromium`
(this is due to [how puppeteer defaults](https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-788199984) based on ARM)
![image](https://user-images.githubusercontent.com/404765/139964520-2b28feed-47f6-4403-b761-d874d8d06af6.png)



Unfortunately Debian 9 uses chromium `73.0.3683.75` and it looks like [Puppeteer `v10.0.0` is using `92.0.4512.0`](https://github.com/puppeteer/puppeteer/releases/tag/v10.0.0)

The version difference (or just the Debain version of chromium) is leading to slight differences in rendering, so this wouldn't be backward compatible; but it did render the same across an Intel versus ARM Mac.

I could share the Docker Image I made for people in this scenario (after more testing) or Backstop itself could publish one using the changes above.
(In my Docker image I upgraded node to `FROM node:16.3.0` in the Dockerfile to get a newer version of Debian and therefore chromium `89.0.4389.114`)

Alternatively we'll have to wait for puppeteer to include an arm64 version of chromium. https://github.com/puppeteer/puppeteer/issues/7740

**Comment by garris** [comment] 2021-11-03 04:45
@cdeutsch thank you for this workaround!  I'd like to see if the puppeteer team has any response to your request before making an official BackstopJS patch (the rendering difference will likely cause some headaches)  Let's give it a week or so.  Cheers!

**Comment by weitzman** [comment] 2021-11-23 01:20
Could use this on my project. Thanks for your efforts, @garris, @cdeutsch and all.

**Comment by DEfusion** [comment] 2021-12-06 13:16
@cdeutsch workaround kind of got things working for me on my Mac, however with lots of tests it just hangs after taking the last screenshot, doesn't seem to with smaller test numbers if I use filtering.

Sadly it is failing completely for me on CI, not closing the browser, i.e. opens the 10 that I have set in concurrency but just sits after trying to close them all until CI times it out.

**Comment by cdeutsch** [comment] 2021-12-06 16:28
@DEfusion I have `asyncCaptureLimit: 1` and `asyncCompareLimit: 10`

I occasionally get hangs after 3 or 4 full runs. No idea why. 

I had similar issues using stock backstop 4.3.2 and always assumed it was the quirky frontend I was trying to test.

**Comment by DEfusion** [comment] 2021-12-06 17:24
> I have `asyncCaptureLimit: 1` and `asyncCompareLimit: 10`

I tried that locally and on CI but sadly still getting hangs on CI; stopped at 133/492 scenarios at Close Browser again. I've had issues with it hanging in the past (pre M1) when the compare limit was high locally (usually with big images to compare) and have tried to dig into Backstop to see why, guess I'll give that another look.

**Comment by garris** [comment] 2021-12-08 02:58
Wow -- great progress! 

If we make this change would this break anything for puppeteer+docker users?   Maybe just rendering differences?

**Comment by cjbd** [comment] 2022-01-20 05:58
> 

hello, @cdeutsch , can you please share your docker file? thank you!

**Comment by cdeutsch** [comment] 2022-01-20 16:43
@cjbd [dockerman33/backstopjs:5.4.4](https://hub.docker.com/r/dockerman33/backstopjs)

**Comment by cjbd** [comment] 2022-01-21 08:53
@cdeutsch, thank you! can you please share the `dockerfile` content, i'm planning to create my own docker which uses `puppeteer`, thanks a lot!

**Comment by cdeutsch** [comment] 2022-01-21 17:18
@cjbd 

```
FROM node:16.3.0

ARG BACKSTOPJS_VERSION

ENV \
	BACKSTOPJS_VERSION=$BACKSTOPJS_VERSION

# Base packages
RUN apt-get update && \
	apt-get install -y git sudo software-properties-common

RUN sudo PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install -g --unsafe-perm=true --allow-root backstopjs@${BACKSTOPJS_VERSION}

RUN wget https://dl-ssl.google.com/linux/linux_signing_key.pub && sudo apt-key add linux_signing_key.pub
RUN sudo add-apt-repository "deb http://dl.google.com/linux/chrome/deb/ stable main"

# RUN	apt-get -y update && apt-get -y install google-chrome-stable

# RUN apt-get install -y firefox-esr

# gconf-service libxext6.... added for https://github.com/garris/BackstopJS/issues/1225

RUN apt-get -qqy update \
  && apt-get -qqy --no-install-recommends install \
    chromium \
    libfontconfig \
    libfreetype6 \
    xfonts-cyrillic \
    xfonts-scalable \
    fonts-liberation \
    fonts-ipafont-gothic \
    fonts-wqy-zenhei \
    gconf-service libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxss1 libxtst6 libappindicator1 libnss3 libasound2 libatk1.0-0 libc6 ca-certificates fonts-liberation lsb-release xdg-utils wget \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get -qyy clean


WORKDIR /src

ENTRYPOINT ["backstop"]
```

Here's what I changed vs commit 6a30f1f

![image](https://user-images.githubusercontent.com/404765/150570912-de841a4c-0034-421e-9061-1fe78ae6396d.png)

**Comment by cjbd** [comment] 2022-01-24 03:23
@cdeutsch , thanks a lot!

**Comment by cdeutsch** [comment] 2022-03-16 13:44
> Any way to get this working without me having to manually modify the Docker image would be greatly appreciated.

@d3vl1m3 you can use my docker image (if you trust it)

[dockerman33/backstopjs:5.4.4](https://hub.docker.com/r/dockerman33/backstopjs)

In your project, adjust the `dockerCommandTemplate` to point to it, and change the `executablePath`

```js
{
  // Add the ` --net="host"` param for Linux.
  dockerCommandTemplate: 'docker run --rm -i --net="host" --mount type=bind,source="{cwd}",target=/src dockerman33/backstopjs:5.4.4 {backstopCommand} {args}',
  engineOptions: {
    args: ['--no-sandbox'],
    executablePath: '/usr/bin/chromium',
  }
}
```

**Comment by d3vl1m3** [comment] 2022-03-16 14:44
Amazing. That was exactly the snippet I was looking for 🥳  

Added that to my local config and will run with it until Puppeteer throw a fix out

Thanks so much @cdeutsch!! 😁

**Comment by Degix** [comment] 2022-03-29 15:31
Thanks @cdeutsch! Your changes working like a charm. 
Sucessfully build backstopjs for `linux/arm64/v8 and linux/amd64` on my Mac Pro (M1). 
Idk why but when i added linux/arm/v7 i couldn't push to my repo and i got auth issues. 
Maybe somebody is running into the same problem...

Dockerfile changes as mentioned by @cdeutsch [here](https://user-images.githubusercontent.com/404765/150570912-de841a4c-0034-421e-9061-1fe78ae6396d.png) :
```
ARG ARCH=
Edited: FROM ${ARCH}node:16.14.0

RUN sudo PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install -g --unsafe-perm=true --allow-root backstopjs@${BACKSTOPJS_VERSION}

RUN apt-get -qqy update \
  && apt-get -qqy --no-install-recommends install \

+  chromium \
```

Before WORKDIR /src:
`RUN ln -s /usr/bin/chromium /usr/bin/chromium-browser`

I also added this symlink to the new arch images, therefore i don't need to change or add the executablePath on e.g. Mac.

Added this to package.json:
`   
 "docker-crossplatform": "PV=$(node -p -e \"require('./package.json').version\"); docker buildx build --output=type=image,push=true --platform linux/arm64/v8,linux/amd64 --tag my.repo.net/backstopjs/backstopjs:$PV ./docker",
`

Run:
npm run docker-crossplatform

Enjoy 👍

**Comment by craigt-ag** [comment] 2022-04-08 05:52
Any updates on this? Workarounds are just that at the moment, not really solving the issue at hand particular to the actual Docker images that BackstopJS provides? @garris love your work btw, would appreciate a word on this.

**Comment by garris** [comment] 2022-04-08 20:48
Hi @craigt-ag -- thank you the kind words and the question on this issue!
And thank you @Degix for the summary solution.

It looks like this is working for a lot of users.  I have some questions about it and I am hoping you guys (or anyone else) can help me understand the nuances of this solution and build enough confidence to push this out.

1. Are the docker changes above compatible with Win and Linux and intel macs?  Can someone do a sanity check?
2. Does this create a "universal" artifact -- iow: once this is built I can just publish the output to docker using the same command as the current container file?
3. Will I be able to build and publish this docker archive project on my intel mac? 
4. If all of the above are yes... Would someone mind do a PR? 🙏

**Comment by cdeutsch** [comment] 2022-04-12 14:25
#### 1. Are the docker changes above compatible with Win and Linux and intel macs? Can someone do a sanity check?

I can confirm the image I built works on M1 and Intel Macs, as well as Ubuntu as part of GitHub CI (which I assume is x86)

I don't have a Windows PC

#### 2. Does this create a "universal" artifact -- iow: once this is built I can just publish the output to docker using the same command as the current container file?

I don't recall having to do anything special to publish, but I can't say for sure either.

#### 3. Will I be able to build and publish this docker archive project on my intel mac?

According to [this article](https://itnext.io/building-multi-cpu-architecture-docker-images-for-arm-and-x86-1-the-basics-2fa97869a99b) it sounds like you can use `buildx` on your Intel based Mac

> On your local dev PC (either x86 or apple M1 CPU), the easiest way to access “Buildx” & “BuildKit” is to install [Docker Desktop](https://www.docker.com/products/docker-desktop). As long as the “experimental” & “buildkit” config options in the docker config file are set to true, you should be able to access Buildx docker CLI plugin & buildkit from the terminal without any special setup.

#### 4. If all of the above are yes... Would someone mind do a PR?

It's not clear the best way to install chromium and adjust the path. Sounds like people are doing it slightly different.

Also, in my experience screenshots weren't backward compatible due to using a newer version of Chrome.

If I find time I'll revisit it.

**Comment by garris** [comment] 2022-04-13 04:05
Ok Great!  Really appreciate all the interest in this. 

Cheers

**Comment by mikemadison13** [comment] 2022-06-03 14:59
FYI it looks like the puppeteer issue has been merged and released.

**Comment by garris** [comment] 2022-06-03 16:38
Thanks for this update @mikemadison13!   So then -- I guess we can back out the PR above?  Please LMK.   Thanks!

**Comment by garris** [comment] 2022-06-04 01:57
Bumped to puppeteer version 14.2.1 with ee8c0ffcf2d13698fc6f6c4de6ed9b6af9d1c6cc

published to NPM
```
+ backstopjs@6.0.5
```

Pushed to docker hub
```
6.0.5: digest: sha256:0f3c000d59557a11d7db3048e8cfa07e2eef04a6bd91cbb0173b14d9049497a3 size: 3474
```

**Comment by cdeutsch** [comment] 2022-06-06 14:24
> FYI it looks like the puppeteer issue has been merged and released.

We'll have to confirm it solves the issue. Unfortunately I think I was mistaken in thinking it would. 

For my scenario (running BackstopJs in Docker) I think I need a Debian Arm build of Chrome (not Apple Silicon) 😞 

https://github.com/puppeteer/puppeteer/pull/7546#issuecomment-1117696403

**Comment by garris** [comment] 2022-06-10 02:10
Ok -- then we are back to this ... https://github.com/garris/BackstopJS/issues/1300#issuecomment-1096799855

I need someone out there to make a strong recommendation for how we should resolve this.   I don't know enough about docker to solve this in this decade.

@cdeutsch had the most viable assessment so far.  I think the rendering differences (called out in item 4) are unavoidable and this would simply have to be a breaking (but manageable) change. 

Seems we would just need a robust way to deal with the chrome path.

And someone needs to spell things out for me in terms of implementation and testing.

If anyone has time to help figure the rest out then I am happy to pull in a fix!

**Comment by cdeutsch** [comment] 2022-06-10 12:54
My work got busy, but it's still on my radar if I can find time. I'm not a linux guru so figuring out the best way to get chromium to work in the docker container and still support path will be the hardest part.

**Comment by mikemadison13** [comment] 2022-06-10 13:59
Is it possible to explore decoupling chromium? Using Behat and some of the other testing frameworks this hasn't been so painful, because Behat itself doesn't include Chromium. So, I can spin up a Chromium service in my docker setup and then just point Behat at that running service. 

I think part of the pain here comes from Puppeteer itself trying to install Chrome/Chromium from NPM and having issues due to the binary.

**Comment by garris** [comment] 2022-06-10 14:49
@mikemadison13 that is what @cdeutsch did above. There are just some details which need to be ironed out wrt validating that this solution will build and run universally. 

Also, a question I haven't asked yet... I don't really understand why some versions of chrome won't run in a container hosted on different hardware.  I thought container architecture solved this problem.  Maybe there is an article someone could recommend?

**Comment by Degix** [comment] 2022-08-26 09:18
Update:
I repeated the steps mentioned above for Version 6.1.1.

A list.manifest.json will be created and showing `linux/amd64` and `linux/arm64`.
Windows users have fetched the linux/amd64 with Chromium download disabled as well. So they needed to add this to their docker-template to find the chrome executable.
`-e PUPPETEER_EXECUTABLE_PATH='node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome'`

I dont know if Windows users would fetch the arm64 arch image if I only build it only for arm64, but i think so. 

Therefore I stumbled up on docker buildx imagetools create. 
With that, you can combine existing images and combine them to one (multi-arch) image. 
I've looked up the BackstopJS official 6.1.1 sha256 and my already uploaded one for the arm64 arch and combined them.
Now the linux/amd64 refers to the offical image and the arm64 one is refering to my fixed one.

(!) You can add --dry-run so you can see the output of the list.manifest first and it won't be pushed directly

The command i've used was:  
`
docker buildx imagetools create myrepo/backstopjs/backstopjs@sha256:0f3c000d59557a11d7db3048e8cfa07e2eef04a6bd91cbb0173b14d9049497a3 sha256:5c705236b9d1d899cfb94b3263e1bbce8570e2d81ccbc8aa7287b592363a0d31 -t myrepo/backstop/backstopjs:6.1.1`

I'm currently very busy as well, but maybe i'll try to play around and when I have success I will create an MR/PR.

**Comment by dkarlovi** [comment] 2022-10-10 14:57
@garris from my understanding of the issue, the changes would be totally unrelated to the current Docker image. It would be like you have separate images, they would only share the name and version number.

When the build is done, the images are published with their name, version and architecture.

When a current user pulls the Backstop image, they get the current image. When the M1 user pulls the image, they'd get the ARM version of the image (as in, it would be a different image). Here's some information about it:
https://gist.github.com/ciaranmcnulty/f82e710668ee285473ea724c83dd51ec

Here's [an example image](https://hub.docker.com/layers/jakzal/phpqa/1.78.0-alpine/images/sha256-c0e433af534db6306306a3107297c3ad05d29ad78b0442eb19aea1633e4e03c0?context=explore) using separate architectures (notice the "OS/ARCH" dropdown) and here's [how the GitHub actions for the image look like](https://github.com/jakzal/phpqa/blob/master/.github/workflows/build.yml). [The `Dockerfile`](https://github.com/jakzal/phpqa/blob/master/Dockerfile) uses a `BUILDPLATFORM` build argument.

**Comment by ukrutt** [comment] 2023-02-09 21:56
There seems to be a new version of Docker that fixes this issue (at least it fixed it for me.) My setup:

 - BackstopJS v5.4.4
 - macOS 13.2 / Ventura (I had to upgrade from 12 to see the checkbox in step 3.)
 - Docker v4.16.2
 - In Docker Settings -> Features in development, check the box "Use Rosetta for x86/amd64 emulation on Apple Silicon".

My tests run well now (albeit possibly slower than they do on an Intel Mac.)

**Comment by tkrah** [comment] 2023-03-14 20:00
@garris If I would create a PR to include support for a multiarch docker build (amd64, arm64) - would you consider to merge that - just asking before I am going to put free time my  on this ;)?

**Comment by garris** [comment] 2023-03-15 00:11
@tkrah Thank you so much for the offer here.  Yes I would consider this -- but I would want to understand the impact...  I have a very simple build & deploy process -- would like to understand what kind of changes I would need to make on my end -- for example, I assume I would have to push multiple docker builds etc. 

But also -- and possibly more important, @ukrutt [mentioned here](https://github.com/garris/BackstopJS/issues/1300#issuecomment-1424888520) that simply bumping versions resolved the issue.   Was wondering if you had tried this and what were the results?

**Comment by tkrah** [comment] 2023-03-15 09:41
ukrutts solution does not help, it is still emulated with rosetta and still too slow to be useful if you want to have acceptable runtimes with many tests, a native image is the solution to the problem.
Ok I'll try to prepare a PR and then we can discuss the impact there.

**Comment by FinnBueno** [comment] 2023-03-21 16:17
Has the docker-image been updated to reflect the latest change? From what I can tell, https://hub.docker.com/r/backstopjs/backstopjs/ was last updated 5 months ago. Seeing this was merged 5 days ago, I'm going to assume that the currently hosted image doesn't include these changes yet.

**Comment by tkrah** [comment] 2023-03-21 16:23
> Has the docker-image been updated to reflect the latest change? From what I can tell, https://hub.docker.com/r/backstopjs/backstopjs/ was last updated 5 months ago. Seeing this was merged 5 days ago, I'm going to assume that the currently hosted image doesn't include these changes yet.

@FinnBueno No of cause this is not yet released, it was merged yesterday btw. @garris is working on that I assume for version 6.2.0.

**Comment by tkrah** [comment] 2023-03-21 17:00
> > @FinnBueno No of cause this is not yet released, it was merged yesterday btw. @garris is working on that I assume for version 6.2.0. But you can now build your own image for the time being with backstopjs 6.1.4 like written in the README.md of the docker folder and use that until it is released.
> 
> My bad, I now see that it was indeed merged yesterday. I asked because me and my team actually hit this roadblock today and I was very glad to see a solution was just merged. I'll be trying to run this with a self-built image for now, thanks!

What a lucky coincidence that I did that PR last week 😂 I hope it works for you and your team.

**Comment by garris** [comment] 2023-03-22 01:54
I can confirm that I am indeed working to get @tkrah 's solution out -- I hope to push new docker builds out tomorrow morning before my day explodes 😅

**Comment by garris** [comment] 2023-03-22 14:53
📣 New docker arm64 support for Apple Silicon has been deployed!   Many thanks to @tkrah for this fix addressing the issue dating back at least 2 years!

Please post your results here if there are any issues.   Cheers!

**Comment by tkrah** [comment] 2023-03-31 19:39
@garris can be closed here imho - people open new issues anyway already ;-). btw you missed to create or push the 6.2.0 tag.

**Comment by garris** [comment] 2023-04-01 01:36
Thank you.  Yes,  I will push a new version soon.

**Closed** 2023-04-01 01:37 UTC
