### ISSUE TITLE
openReport does not open Report

### ISSUE THREAD

**Issue by Primajin** [garris/BackstopJS#305] opened 2016-10-07 13:40 UTC
```
> backstop openReport

BackstopJS CWD:  /my-path
BackstopJS loading config:  /my-path/backstop.json

COMMAND | Executing core for `openReport`
openReport | Opening report.
openReport | An error occured while opening report in the default browser.
   COMMAND | Command `openReport` sucessfully executed
```

So nothing happens, no Browser opens - despite which I set as default.
- MBP with macOS 10.12

**Comment by garris** [comment] 2016-10-07 18:10
Need to look into this.

**Comment by angelariggs** [comment] 2016-10-07 23:29
I'm having the same issue as @Primajin. Additional info in case it's related: when I run my `backstop test` command, a `config.js` file is not getting generated in the `backstop_data` folder.

**Comment by garris** [comment] 2016-10-07 23:31
👀

**Comment by garris** [comment] 2016-10-07 23:36
Yup.  it's a bug alright.  This happens when any of the comparisons fail.   Looking at this now.

**Comment by angelariggs** [comment] 2016-10-07 23:40
I had all passing tests, according to the CLI report. 
![screen shot 2016-10-07 at 4 39 30 pm](https://cloud.githubusercontent.com/assets/10238548/19208229/a822c152-8cac-11e6-9521-67bb45a493e1.png)

**Comment by garris** [comment] 2016-10-07 23:42
hmm.  then maybe it's not related to pass/fail.   I just used the genConfig template.  Does that work for you?

**Comment by garris** [comment] 2016-10-07 23:44
It looks like there is an error when opening the report.  Are you on macOS?

**Comment by garris** [comment] 2016-10-07 23:49
Yup confirmed.  not related to pass/fail.

**Comment by garris** [comment] 2016-10-07 23:52
Ok.  I can't reproduce this issue...

![image](https://cloud.githubusercontent.com/assets/447033/19208412/61fb6b1e-8cae-11e6-88b4-3c57ba77d84d.png)

**Comment by garris** [comment] 2016-10-07 23:58
Ok.  I can reproduce it.

Does your config have an empty report prop?  e.g. 
```
...
  "report": [],
...
```

**Comment by angelariggs** [comment] 2016-10-08 00:01
My report property is "report": ["browser, CLI"]. The genConfig command did generate the config template, but then I changed the name to `prod_backstop.json` (and allowed for that when running subsequent commands).

**Comment by garris** [comment] 2016-10-08 00:04
Does it work for you if you just change it to `"report": ["browser"]`

**Comment by angelariggs** [comment] 2016-10-08 00:07
Yes! 🎉  Was the CLI option just part of 1.x?

**Comment by garris** [comment] 2016-10-08 00:09
WOOHOO! 

And yes, Version2 is a proper CLI now -- it's always on so you don't need that bit.

**Comment by garris** [comment] 2016-10-08 00:10
So glad we got that before the weekend! 😄   Thank you for helping me troubleshoot  -- much appreciated!

**Comment by garris** [comment] 2016-10-08 00:12
@Primajin does this solve your issue also?

**Comment by angelariggs** [comment] 2016-10-08 00:13
Woohoo! 😄  Thanks for being so responsive! Enjoy your weekend!

**Comment by garris** [comment] 2016-10-08 00:14
I will take a look at that logic -- it should have been backward compatible...   and perhaps we should always generate the HTML report and just use the `"browser"` flag to auto-open the browser (because that can be annoying when you don't want it.)

**Comment by Primajin** [comment] 2016-10-08 07:49
Allright guys, will give it a try when I'm back in the office on Monday. I too had CLI / CI in reporters, since I only need it on command line in Travis.

Also all my images fail on Travis in v2x while working in v1x - will dig deeper into that and open an Issue when I'm sure it's not on my side ;)
Thanks so far in advance!

**Comment by garris** [comment] 2016-10-08 18:29
@Primajin thanks for looking at this -- I am what you find will help other users who are migrating!

Also, FWIW:  please note the documentation for migrating to 2.x -- I.e. different way to call `backstop <command>` and different path references.

Awesome.

**Comment by Primajin** [comment] 2016-10-10 10:48
Ahh now I get it! The Report in V2 is now just a plain static file that shows what the CLI did, just a bit nicer - it is not doing the actual comparison anymore as in v1!

**Comment by Primajin** [comment] 2016-10-10 11:00
ok then it's clear now: without "browser" in reporters no file gets generated and so no report can be opened. Solutions:

- have a setting like `"html"` where html report is generated but openReport (eg. firing up the browser) is not invoked
- have a better error handling: When `openReport` is used but no file was found, tell the user that report file is missing / was not generated.

---------

I still have not found out why v2 comparison is failing in travis while working fine on my local machine. Also it's behaving really weird, it checks all images, fails then starts over again then hangs up the process.... 🤔  Will dig a little more....else I need to file a new issue 😉

**Comment by garris** [comment] 2016-10-10 23:22
I am thinking it's better to just generate the HTML report regardless.  Yes it's more work -- but it is a very very small amount of work.  Then use the "browser" value to run the `openBrowser` segment.  This way I think it will behave in an intuitive way for most users.

**Comment by garris** [comment] 2016-10-10 23:25
If you can figure out why your v2 is failing that would be great as I will not have any time this week.  When troubleshooting pay special attention to your config `paths` node (paths should not use the old `../../` pattern) and make sure you are running from your project root -- not the /node_modules/backstopjs directory.   

Thank you!

**Comment by Primajin** [comment] 2016-10-11 05:17
Configuration seems "fine" as I found out that some files pass but most don't (with the same script locally all pass). I'm currently struggling to get the generated files from the short living Travis VM to my local machine to actually have a look at the files to figure out why they might fail. I can ssh into a Travis VM when it runs in debug mode, but it won't let me scp files. With Backstop V1 when the build failed I could order Travis to upload the files to Amazon S3 - where I could have a look at the images. But in v2 it seems to fail... differently so Travis hangs up the process and does not upload the failed files...
So if anyone has an idea how I can get the generated images down from Travis - would be great!

**Comment by garris** [comment] 2016-10-11 16:14
@Primajin so is it safe to say that the openReport issue is resolved for you by updating the config to include "browser"?  I think we might create a separate ticket for your other issue.

**Comment by Primajin** [comment] 2016-10-11 20:01
Yes! Let's resolve this and move the discussion to a new issue

**Comment by garris** [comment] 2016-10-11 20:19
@Primajin thanks!   I made a change to implement always generating html reports -- with only opening on `report: ["browser"]` value.   Will push that soon.

**Comment by garris** [comment] 2016-10-12 18:01
@Primajin -- I pushed the html report enhancement yesterday to master 
```
npm install -g garris/backstopjs#master
```
you should now be able to openReport regardless of the `report` config setting.   Feel free to check it.   Thanks.

**Comment by garris** [comment] 2016-10-16 00:07
I just tested this.  Working as expected.  Closing.

**Closed by garris** 2016-10-16 00:07 UTC
Labels: bug
