### ISSUE TITLE
After some tests It doesn't work anymore

### ISSUE THREAD

**Issue by reynaldoapb** [garris/BackstopJS#659] opened 2018-02-07 13:54 UTC
Could someone tell me why backstop stop to work after some tests? It works on the first 3 time after I turn on my computer...after that it doesn't load any page. Even the default test doesn't work.

**Comment by krzksz** [comment] 2018-02-07 14:32
Hey! This usually mean that there are some zombie Chrome processes left from erroneous tests. Check https://github.com/garris/BackstopJS#error-failed-to-launch-a-browser for possible fixes.

**Comment by garris** [comment] 2018-02-07 16:22
I had similar symptoms— I found there was an unnecessary process (I don’t remember which it was) using ports that backstop used by default.

Try setting config `startingPort` to `9300` to see if that might solve the issue.

**Comment by garris** [comment] 2018-02-07 16:26
Also, addressing #641 would also likely fix this issue.

**Comment by Kenith** [comment] 2018-02-07 17:09
I have the same issue, and found out it is because some "dead chrome" still in the backend.
Try to: **pgrep -c chrome** to see how many chrome stays in backend.
If true, go to here to check solution: https://github.com/garris/BackstopJS/issues/658

**Comment by garris** [comment] 2018-02-13 21:00
This issue should be fixed in latest.   Can someone please validate.

**Comment by mike-malandra** [comment] 2018-03-13 17:28
I'm still getting this issue with BackstopJS v3.1.19 on Windows 10. After running backstop, there are several instances of chrome still open.

I agree that lowering the async capture limit seems to help, but any ideas as to why higher limits are causing these failures?

**Comment by kiran-redhat** [comment] 2018-03-13 18:16
I found setting asyncCaptureLimit 1 helped but otherwise isuue is
intermittent

**Comment by garris** [comment] 2018-03-13 18:50
@mike-malandra can you please confirm if asyncCaptureLimit: 1 enables you to run without exceptions?

**Comment by mike-malandra** [comment] 2018-03-13 19:00
@garris yes, running with 1 or 2 runs without exceptions.

**Comment by garris** [comment] 2018-03-13 19:13
I totally understand.  Are you testing a local app?

**Comment by garris** [comment] 2018-03-13 19:19
I am asking because I want to rule out the possibility that the application environment you are hitting is not dropping because of a burst of hits from backstop tests.  I want to be sure to rule this out — possibly by just creating a simple HTML test page and hitting that 1000 times with a backstop test.

There is also a potential memory issue we may need to consider.

**Comment by mike-malandra** [comment] 2018-03-13 19:34
this is actually a wordpress app (building a POC for our site). I could attempt to test something like google.com to see if I get similar results with a higher async limit.

Also, are there any logs I can view to see if something is dropping?

**Comment by garris** [comment] 2018-03-13 19:43
Please do not test google.  Test a local simple html page.

And you can test with debugging on — and also just check your local sever logs for 500 errors etc.

**Comment by garris** [comment] 2018-03-13 21:11
@mike-malandra  please see this post -- I believe it is the same issue you are having... 
 https://github.com/garris/BackstopJS/issues/696#issuecomment-372815724

If possible, please serve a simple HTML page locally (no images - just some text)  -- you can just repeat the same scenario a hundred times using `asyncCaptureLimit: 10`. The idea is to stress backstop with many concurrent scenarios without stressing your server env.   This would enable us to validate that it is environmental.   You know, _science_.  

You can monitor memory usage with the activity monitor utility.

**Comment by Kenith** [comment] 2018-03-15 07:36
@garris I am testing your latest release: 3.1.19.
And will let you know the result asap.

**Comment by mike-malandra** [comment] 2018-03-15 13:30
@garris the issue does indeed seem to be environmental, as I get the same results on a local HTML page as i do on the wordpress site. Not sure if it's coincidence or not yet, but if i set the number of concurrent tests to the amount of cores my CPU has (8), I get stable results. As soon as I go over that amount, stability begins to deteriorate.  Memory consumption never peaked above 70% while I was running the tests, but there were occasional some spikes in hard faults. 

Also, when running with more than 9 async captures, i got the following message in the console:
`(node:11624) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by garris** [comment] 2018-03-15 14:04
The recommended asyncCaptureLimit is 5.  Is it successful with that value?

**Comment by mike-malandra** [comment] 2018-03-15 16:10
yes it is successful with that value.

**Comment by garris** [comment] 2018-03-15 16:45
Ok,  great.  Thank you for the data point!   Beyond 5 it starts to become diminishing returns.

**Comment by garris** [comment] 2018-03-15 17:12
Now that Backstop detects busy ports and we have established that backstop can run hundreds of tests with a asyncCaptureLimit of 5  — are we able to mark this ticket as closed?

Any remaining concerns here?

**Comment by Kenith** [comment] 2018-03-16 17:43
@garris I confirmed the unstable issue is fixed.

So, I run the same test at home without proxy for serval times with asyncCaptureLimit=5 to capture 600 pages, all good.

You could close the ticket: https://github.com/garris/BackstopJS/issues/663

I have created my own repository for Visual regression test: https://github.com/Kenith/ta-visual-lib
Hope could be the help for the community.

**Comment by garris** [comment] 2018-03-16 19:14
@kenith That’s great!  Thank you for testing and for documenting!  Cheers

**Closed by garris** 2018-03-16 19:14 UTC
