### ISSUE TITLE
SlimerJS not generating reference images

### ISSUE THREAD

**Issue by benjaminfisher** [garris/BackstopJS#173] opened 2016-03-15 19:06 UTC
I've noticed issues with flex-box rendering in PhantomJS, so I tried switching to SlimerJS.
I installed it globally using npm on Windows 7 64bit, and modified the backstop.json file as directed in the README.md file:
```
Then, in your backstop.json config file, update the engine property to...

  "engine": "slimerjs"
```

Running `npm run reference` gives:
```
BackstopJS Config loaded at location C:\Rhythm\rhythm-testing\backstop.js
on
[15:05:01] Using gulpfile C:\Rhythm\rhythm-testing\node_modules\backstopj
s\gulpfile.js
[15:05:02] Starting 'clean'...
bitmaps_reference was cleaned.
[15:05:02] Starting 'bless'...
[15:05:02] Finished 'bless' after 5.4 ms
[15:05:02] Finished 'clean' after 65 ms
[15:05:02] Starting 'reference'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task
triggering instead.
[15:05:02] Starting 'init'...
[15:05:02] Finished 'init' after 5.8 µs
[15:05:02] Starting 'test'...

Generating reference files.


Running CasperJS with:  [ 'capture/genBitmaps.js', '--engine=slimerjs' ]
[15:05:02] Finished 'test' after 17 ms
reference has run.
[15:05:02] Finished 'reference' after 21 ms

Testing script failed with code: 1

Looks like an error occured. You may want to try running `$ npm run echo`
. This will echo the requested test URL output to the console. You can ch
eck this output to verify that the file requested is indeed being receive
d in the expected format.
```

And no image files are generated in the `/backstop_data/bitmaps_reference` folder.

**Comment by garris** [comment] 2016-03-15 19:17
@benjaminfisher I think this is related to your other issue -- maybe tackle this one at a time... https://github.com/garris/BackstopJS/issues/171

Marking as duplicate.

**Comment by garris** [comment] 2016-03-15 22:19
Not a duplicate.

**Comment by benjaminfisher** [comment] 2016-03-17 13:52
With the engine set to slimerjs in the backstop.json config fie I get the following output to the console:

```
$ npm run reference

> rhythm-testing@1.0.0 reference C:\Rhythm\rhythm-testing
> cd node_modules\backstopjs & npm run reference


> backstopjs@1.2.1 reference C:\Rhythm\rhythm-testing\node_modules\backst
opjs
> gulp reference


BackstopJS Config loaded at location C:\Rhythm\rhythm-testing\backstop.json
[09:46:16] Using gulpfile C:\Rhythm\rhythm-testing\node_modules\backstopjs\gulpfile.js
[09:46:16] Starting 'clean'...
bitmaps_reference was cleaned.
[09:46:16] Starting 'bless'...
[09:46:16] Finished 'bless' after 6.82 ms
[09:46:16] Finished 'clean' after 89 ms
[09:46:16] Starting 'reference'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[09:46:16] Starting 'init'...
[09:46:16] Finished 'init' after 4.91 µs
[09:46:16] Starting 'test'...

Generating reference files.


Running CasperJS with:  [ 'capture/genBitmaps.js', '--engine=slimerjs' ]
[09:46:16] Finished 'test' after 14 ms
reference has run.
[09:46:16] Finished 'reference' after 17 ms

Bitmap file generation completed.

Run `$ npm run test` to generate diff report.
```

However no images are created in bitmaps_reference.

**Comment by garris** [comment] 2016-03-21 15:26
Sorry @benjaminfisher,  I can't reproduce this.   Can you confirm there are no files saved in the bitmap_reference folders?  Could you maybe try this on a different machine? 

In trying to reproduce, I _did_ find a bug with the browser report not running properly in some cases -- but I think this is unrelated.

**Comment by Brykou** [comment] 2016-08-23 15:37
I have the same problem. Did you solve this ?

**Comment by Brykou** [comment] 2016-08-24 09:07
My problem was related to https://github.com/garris/BackstopJS/issues/108#issuecomment-151756055

**Comment by garris** [comment] 2016-08-24 13:19
Thanks.

**Closed by garris** 2016-08-24 13:19 UTC
