### ISSUE TITLE
Clean install/run on Windows 10 not working

### ISSUE THREAD

**Issue by patdavid** [garris/BackstopJS#289] opened 2016-09-22 21:26 UTC
Clean install of my site.  The site builds and shows up fine in a browser.  Running backstop is kicking some odd errors that I can't quite figure out.

```
C:\Users\patdavid\Personal\github\pixlsus\website>node --version
v4.5.0

C:\Users\patdavid\Personal\github\pixlsus\website>npm --version
2.5.19
```

I installed your beta:

```
C:\Users\patdavid\Personal\github\pixlsus\website> npm install -g garris/backstopjs#version_2_0
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"4.5.0","npm":"2.15.9"})
\
> phantomjs-prebuilt@2.1.12 install C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt
> node install.js

Considering PhantomJS found at C:\Users\patdavid\AppData\Roaming\npm\phantomjs.CMD
Looks like an `npm install -g` on windows; skipping installed version.
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\patdavid\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...
  [=======================================-] 99%
Received 17767K total.
Extracting zip contents
Removing C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\patdavid\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1474578439927\phantomjs-2.1.1-windows -> C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
C:\Users\patdavid\AppData\Roaming\npm\backstop -> C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs\cli\index.js
backstopjs@2.0.0 C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs
├── lodash.map@4.6.0
├── open@0.0.5
├── minimist@1.2.0
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── node-resemble-js@0.0.4 (pngjs@0.4.0)
├── fs-extra@0.30.0 (path-is-absolute@1.0.0, klaw@1.3.0, jsonfile@2.4.0, graceful-fs@4.1.6, rimraf@2.5.4)
├── casperjs@1.1.3
├── junitwriter@0.3.1 (merge@1.2.0, mkdirp@0.5.0, dateformat@1.0.11, xmlbuilder@2.6.2)
└── phantomjs-prebuilt@2.1.12 (progress@1.1.8, kew@0.7.0, es6-promise@3.2.1, which@1.2.11, request-progress@2.0.1, hasha@2.2.0, extract-zip@1.5.0, request@2.74.0)
```

I have a backstopjs.json that works fine on another install (different computer).  For reference, my backstop.json: https://paste.gnome.org/puwbf4ho6

From the project primary directory, running `>backstop refrence`:

```
C:\Users\patdavid\Personal\github\pixlsus\website>backstop reference

BackstopJS CWD:  C:\Users\patdavid\Personal\github\pixlsus\website
BackstopJS loading config:  C:\Users\patdavid\Personal\github\pixlsus\website\backstop.json

COMMAND | Executing core for `reference`
  clean | bitmaps_reference was cleaned.

Running CasperJS with:  [ 'C:\\Users\\patdavid\\AppData\\Roaming\\npm\\node_modules\\backstopjs\\capture\\genBitmaps.js' ]
CasperJS:  Fatal: The specified executable is not a valid application for this OS platform.; did you install phantomjs?

Testing script failed with code: 4294967295

An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
COMMAND | Command `reference` ended with an error
COMMAND | Error: An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
              at ChildProcess.<anonymous> (C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs\core\util\createBitmaps.js:63:18)
              at emitTwo (events.js:87:13)
              at ChildProcess.emit (events.js:172:7)
              at maybeClose (internal/child_process.js:829:16)
              at Socket.<anonymous> (internal/child_process.js:319:11)
              at emitOne (events.js:77:13)
              at Socket.emit (events.js:169:7)
              at Pipe._onclose (net.js:486:12)
```

Checking on phantomjs: `> phantomjs --version`
`2.1.1`

**Comment by garris** [comment] 2016-09-23 00:10
Hi @patdavid,  thanks for posting!    

This line is kind of bothering me... 
```
CasperJS:  Fatal: The specified executable is not a valid application for this OS platform.; did you install phantomjs?
```

I also see that phantomjs is responding the correct version so that is confusing.

Just for sanity, are you able to create a directory somewhere, `cd` into it and run...
```
backstop genConfig && backstop reference && backstop test
```

That would verify the install.  

Please let me know.  Thanks!

**Comment by patdavid** [comment] 2016-09-23 03:29
```
$ backstop genConfig

BackstopJS CWD:  C:\Users\patdavid\backstop-test
COMMAND | Executing core for `genConfig`
genConfig | Copying 'C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs/capture/casper_scripts' to 'C:\Users\patdavid\backstop-test/backstop_data/casper_scripts'
  COMMAND | Command `genConfig` ended with an error
TypeError: string.split is not a function
    at paddedString (C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs\core\util\logger.js:33:22)
    at message (C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs\core\util\logger.js:59:62)
    at C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs\core\command\index.js:63:18
genConfig | Configuration file written at 'C:\Users\patdavid\backstop-test\backstop.json'
```

**Comment by garris** [comment] 2016-09-23 04:32
@patdavid you may be one of the first win10 users were hearing from so I appreciate the report. :)

@onigoetz could you take a quick look at this?  Any thoughts?

**Comment by garris** [comment] 2016-09-23 06:26
Ok.  From your console output, I am pretty sure it's this...
```
genConfig | Copying 'C:\Users\patdavid\AppData\Roaming\npm\node_modules\backstopjs/capture/casper_scripts' to 'C:\Users\patdavid\backstop-test/backstop_data/casper_scripts
```
I don't think Windows likes its path separators going all over the place...

@patdavid I will try to patch this tomorrow and hopefully you can give it a go on your end.

Thanks.

**Comment by onigoetz** [comment] 2016-09-23 10:13
Hello, 

I think that the first error @patdavid gets is `The specified executable is not a valid application for this OS platform.; did you install phantomjs?"` and is due to the fact that we don't find the windows executable correctly:
- https://github.com/garris/BackstopJS/blob/version_2_0/core/util/runCasper.js#L28
- https://github.com/garris/BackstopJS/blob/version_2_0/core/util/findExecutable.js

It's probably right that windows doesn't like paths with slashes in both directions. but it seems our default configuration has paths specific to *nix.

Then for `string.split is not a function` it seems to come from : https://github.com/garris/BackstopJS/blob/version_2_0/core/util/logger.js#L37

Maybe we should change https://github.com/garris/BackstopJS/blob/version_2_0/core/util/logger.js#L33 from 
```
  if (typeof string !== 'string') {
    return '';
}
```

to  

```
if (!string.split) {
    return string;
}
```

**Comment by garris** [comment] 2016-09-23 17:31
@onigoetz yes, you are totally right about `return string`.  I updated that.  I will also update makeConfig.js to use path.join() on all paths.   

I haven't looked at findExecutable.js yet -- I'll work on makeConfig.js first.

**Comment by garris** [comment] 2016-09-23 17:33
@patdavid I'll let you know when the fixes are in.  For now -- as a workaround, the app is very solid on *nix boxes if that's an option for you.    Thanks again.

**Comment by patdavid** [comment] 2016-09-23 17:43
Thank you all so much for taking the time to help and possibly get a fix!  Much appreciated!

Just an FYI: I've also tried this in a Cygwin environment and unfortunately it still kicks the same errors there as well. :(  I'll try it out from an ubuntu partition!

**Comment by garris** [comment] 2016-09-24 19:55
Ok.  I pushed a patch which resolves the path issues.  I have also been able to reproduce this error on Win10... 
```
CasperJS:  Fatal: The specified executable is not a valid application for this OS platform.; did you install phantomjs?
``` 
I think the phantom install version may be linux only.  Will look at that as soon as I can.  

Would totally appreciate comments if anyone else has insight on the correct phantom install for windows.

**Comment by garris** [comment] 2016-09-28 00:09
@patdavid Thanks for your patience!  I was able to repo the problem and I have pushed a fix.  

Please update your install with...
```
npm install backstopjs@beta -g
```

You can then just run...
```
backstop genConfig && backstop reference && backstop test
```

That is the 3 minute test.   I am pretty confident this will resolve your issue.   Please let me know!

Thanks!

**Comment by patdavid** [comment] 2016-09-28 11:20
Awesome! I'll pull it later today, test, and report back.

**Comment by patdavid** [comment] 2016-09-28 14:18
Followed your instructions and everything appears to be running again!  Thank you so much for your time taking care of this (and creating such a handy project)!

**Comment by patdavid** [comment] 2016-09-28 14:59
Not sure if this should be a separate issue, or if it's related to this one, but the report command errors:

```
 report |
          Test completed...
 report | 17 Passed
 report | 7 Failed

 report | Writing browser report
COMMAND | Command `report` ended with an error
COMMAND | Error: C:\Users\patrickd\Personal\github\pixlsus\website\C:\Users\patrickd\Personal\github\pixlsus\webste\backstop_data contains invalid WIN32 path characters.
              at Object.mkdirs (C:\Users\patrickd\AppData\Roaming\npm\node_modules\backstopjs\node_modules\fs-exta\lib\mkdirs\mkdirs.js:16:20)
              at C:\Users\patrickd\AppData\Roaming\npm\node_modules\backstopjs\node_modules\fs-extra\lib\copy\cop.js:36:13
              at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
COMMAND | Command `test` ended with an error
COMMAND | Error: C:\Users\patrickd\Personal\github\pixlsus\website\C:\Users\patrickd\Personal\github\pixlsus\webste\backstop_data contains invalid WIN32 path characters.
              at Object.mkdirs (C:\Users\patrickd\AppData\Roaming\npm\node_modules\backstopjs\node_modules\fs-exta\lib\mkdirs\mkdirs.js:16:20)
              at C:\Users\patrickd\AppData\Roaming\npm\node_modules\backstopjs\node_modules\fs-extra\lib\copy\cop.js:36:13
              at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
```

It's not a showstopper for me, as I can just pull up the failed*.png referenced in the output, but wanted to be thorough... :D

**Comment by garris** [comment] 2016-09-28 17:23
Hmm.  I think this is unrelated to the first issue -- but probably also due to the refactor.   Would you mind creating a new ticket?  Please include your config.  Thank you.

**Comment by patdavid** [comment] 2016-09-28 18:45
Turns out I was simply missing `"html_report"` from the `"paths"`.  All set now - thanks!

**Comment by garris** [comment] 2016-09-28 18:53
Thanks for figuring that out!   I'll add a ticket to look at the `html_report` default value.  Cheers!

**Closed by garris** 2016-09-28 18:53 UTC
Labels: bug
