### ISSUE TITLE
Tests complete, but HTML report isn't updated

### ISSUE THREAD

**Issue by keithjgrant** [garris/BackstopJS#359] opened 2016-11-30 19:41 UTC
My tests run correctly, and new images are generated in the bitmaps_test directory, but the html_report isn’t being generated/updated.

So, the backstory: I'm doing a major rework of my CSS in a branch (converting from Less to PostCSS). I discovered Backstop, and thought I could use it to help me catch mistakes in the conversion. I went into my master branch, setup Backstop, and it seemed to work perfectly. I then merged those changes (including bitmaps_references) into the working branch. Now, when I run tests, most of them fail (expected, as I’m mid-process), but the HTML report isn't being generated.

There are no errors logged, but there are a lot of test failures, as expected. Then output just stops. There is no "tests completed" or pass/fail count logged, and no browser report. The final lines of output:

```
compare | OK: Components igw_Components_1_kss-modifier__example__n1_0_medium.png
compare | ERROR { size: isDifferent, content: 0.00%, threshold: 0.1% }: Components igw_Components_5_kss-modifier__example__n5_0_medium.png
   See: /Users/kgrant/src/web/icegroupweb-styles/backstop_data/bitmaps_test/20161130-132948/failed_diff_igw_Components_5_kss-modifier__example__n5_0_medium.png
compare | ERROR { size: isDifferent, content: 0.00%, threshold: 0.1% }: Components igw_Components_4_kss-modifier__example__n4_0_medium.png
   See: /Users/kgrant/src/web/icegroupweb-styles/backstop_data/bitmaps_test/20161130-132948/failed_diff_igw_Components_4_kss-modifier__example__n4_0_medium.png
compare | ERROR { size: isDifferent, content: 0.00%, threshold: 0.1% }: Components igw_Components_3_kss-modifier__example__n3_0_medium.png
   See: /Users/kgrant/src/web/icegroupweb-styles/backstop_data/bitmaps_test/20161130-132948/failed_diff_igw_Components_3_kss-modifier__example__n3_0_medium.png
compare | ERROR { size: isDifferent, content: 0.00%, threshold: 0.1% }: Components igw_Components_2_kss-modifier__example__n2_0_medium.png
   See: /Users/kgrant/src/web/icegroupweb-styles/backstop_data/bitmaps_test/20161130-132948/failed_diff_igw_Components_2_kss-modifier__example__n2_0_medium.png
compare | ERROR { size: ok, content: 2.69%, threshold: 0.1% }: Components igw_Components_0_kss-modifier__example_0_medium.png
   See: /Users/kgrant/src/web/icegroupweb-styles/backstop_data/bitmaps_test/20161130-132948/failed_diff_igw_Components_0_kss-modifier__example_0_medium.png
compare | ERROR { size: isDifferent, content: 55.25%, threshold: 0.1% }: Components igw_Components_7_kss-modifier__example__n7_0_medium.png
   See: /Users/kgrant/src/web/icegroupweb-styles/backstop_data/bitmaps_test/20161130-132948/failed_diff_igw_Components_7_kss-modifier__example__n7_0_medium.png
compare | ERROR { size: isDifferent, content: 9.01%, threshold: 0.1% }: Components igw_Components_29_kss-modifier__example__n29_0_medium.png
   See: /Users/kgrant/src/web/icegroupweb-styles/backstop_data/bitmaps_test/20161130-132948/failed_diff_igw_Components_29_kss-modifier__example__n29_0_medium.png
$
```

It's possible there are a different number of generated images now, though I‘m not certain. Could this be caused by an inability to match up reference images to test images 1:1?

**Comment by cilefen** [comment] 2017-02-10 00:06
+1 I have the same thing

**Comment by cilefen** [comment] 2017-02-10 00:11
@keithjgrant Did you ever find the solution? I think the amount of tests is involved because if I use `--filter` to run fewer, the report is created.

**Comment by cilefen** [comment] 2017-02-10 12:44
For me, this turned out to be one problematic image compare, which was the last one listed in the command output before it silently dies.

**Comment by aperkaz** [comment] 2018-01-25 08:34
Hello @cilefen,
Any solutions for this yet? I am facing the same issue as the tests pass but the report is not being generated.
Thanks

**Comment by cilefen** [comment] 2018-01-25 12:11
@aperkaz Right now make sure you haven’t accidentally installed a pre release. There’s a problem with that I recall.

**Comment by garris** [comment] 2018-01-25 17:36
Not really sure what's going on there.  You might just want to save a copy of your references then run `backstop init` which will blow away all of your existing data.  Then add back the references and try `backstop test`.   Also, maybe just try running `pkill -f "(chrome)?(--headless)"` to make sure you don't have any zombie chrome processes running.   If that doesn't work you'll need to post your config.   

In general backstop is great for keeping things under control when refactoring CSS.

**Comment by aperkaz** [comment] 2018-01-29 07:34
Thanks for the fast response @garris and taking the time to dig into the issue. 
The solution then is to roll back and forth with the versions, or there is a  better option? 
Thanks 🙂

**Comment by garris** [comment] 2018-01-29 14:12
No.  That would be ridiculous.   I was just documenting what happened.  The root cause is still unknown.

**Comment by webhamm** [comment] 2018-05-15 14:41
@garris is there a command or hack to run only the comparisons so I don't have to regenerate the test images. That is 90% of the processing time.

**Comment by garris** [comment] 2018-05-15 16:12
At this point I am recommending that everyone migrate to the latest release with the puppeteer engine.   Puppeteer is much more stable for heavier workloads.   At work we have very very thick clients and prior were running small config batches -- which actually worked fine in most cases.   But the puppeteer engine runs way faster and is much better about error handling.

Please give it a try.

**Comment by nsp27** [comment] 2019-01-09 21:37
I am using backstop version 3.8.5 and running with puppeteer headless in my enterprise docker. Test runs absolutely fine and also create difference in backstop_data with the time stamp also prints the difference in the console however html report dont get generated.  Any thought would really be appreciated? Thanks

**Comment by garris** [comment] 2019-01-10 08:14
Here is a sanity test you can run to test if the docker implementation is working in your environment...

https://github.com/garris/BackstopJS/blob/master/README.md#sanity-test-does-backstop-work-in-my-environment

Does this work?

**Comment by cilefen** [comment] 2019-01-10 19:51
Good to hear. I vote we close this issue as outdated.

**Comment by garris** [comment] 2019-01-11 05:39
+1

**Closed by garris** 2019-01-11 05:39 UTC

**Comment by dalin-** [comment] 2020-05-12 14:54
@nsp27 's suggestion didn't work for me.  For now I'm just removing the scenario that was causing the error.

**Comment by Bobrovskih** [comment] 2020-12-23 16:40
I didn't get the report either v4.4.2 or v5.0.7. I spent a lot of time searching and debugging.
In the end, I changed the parameter `asyncCompareLimit: 25` (before it was 50) and the problem solved.
